In [2]:
import numpy as np


In [3]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

> Matrix subtraction

In [4]:
profit = revenue-expenses

In [5]:
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

> Matrix Multiplication

In [6]:
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [7]:
price_per_unit*units

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

> Dot Product

In [9]:
np.dot(price_per_unit,units)

array([34400, 50000, 64400])

>Exercise 1:-<br>
some indian companies revenues in US dollars. Using numpy can you convert this into Indian rupees? 1 USD = 75 INR

In [10]:
rev = np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
inr = np.array([75])

In [11]:
rev *inr

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

>Exercise 2:-<br>
Divine flowers is a flower shop that sells different type of flowers. Below is the table showing how many flowers of each type they sold in different months. Also given are the prices of one flower each. Using this find out their total sales in every month.

In [13]:
unit= np.array([[50,60,25],[10,13,5],[40,70,52]])
priceperunit = np.array([20,30,15])

In [15]:
np.dot(priceperunit,unit)

array([1900, 2640, 1430])

>Here is some matrix exercise from mathisfun.com. Please click on a link below and do the exercise. <br><br>

<a href = "https://www.mathopolis.com/questions/q.html?id=714&t=mif&qs=714_715_716_717_2394_2395_2397_2396_8473_8474_8475_8476&site=1&ref=2f616c67656272612f6d61747269782d6d756c7469706c79696e672e68746d6c&title=486f7720746f204d756c7469706c79204d61747269636573">Click me for matrix exercise</a>