Explained MSE,log loss, MAE

> Tensorflow loss values examples<br>
<ul>
<li> sparse_categorical_crossentropy</li>
<li> binary_crossentropy</li>
<li>categorical_crossentropy</li>
<li>mean_absolute_error</li>
<li> mean_squared_error</li>
</ul>

> Loss is used in the neural networking training

Total error = error1 + error2 + ....+errorn<br>
eer

> Individual errors is known as **Loss** <br>
>Cumilative error or mean absolute error is known as **cost error**

> **epochs** means going through all the training samples ones<br>
epochs = 5; means going through all the tarining samples 5 times

> For **logistic regression** we use **log loss** function

For **Regression** - **MSE**,**MAE**,**Huberloss**<br>
For **Classification** - **Binary cross Entropy**(Binary Classification), **Categorical Cross Entropy**(Multiclass classification)

> **MEAN ABSOLUTE ERROR**

Loss function = (1/n)x|y-y&#770;|<br>
Cost function = (1/n)x&sum;<sub>i=1</sub><sup>n</sup>|y-y&#770;|

In [1]:
import numpy as np

In [19]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [8]:
def mae(y_true,y_preedicted):
    total_error = 0
    for yt,yp in zip(y_true,y_predicted):
        print(yt,yp)

In [9]:
mae(y_true,y_predicted)

0.3 1
0.7 1
1.0 0
0.0 0
0.5 1


In [14]:
def mae(y_true,y_predicted):
    total_error = 0
    for yt,yp in zip(y_true,y_predicted):
        total_error += abs(yt-yp)
    print("Total error: ",total_error)
    mae = total_error/len(y_true)
    print("MAE : ",mae)
    return mae

In [15]:
mae(y_true,y_predicted)

Total error:  2.5
MAE :  0.5


0.5

In [20]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [21]:
y_predicted-y_true

array([ 0.7,  0.3, -1. ,  0. ,  0.5])

In [22]:
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [23]:
# MAE using numpy
np.mean(np.abs(y_predicted-y_true))

0.5

In [24]:
# total error using numpy
np.sum(np.abs(y_predicted-y_true))

2.5

**Advantages**<br>
- Robust to outliers
- Differntiable by doing subgradients

>**LOG LOSS FUNCTION**

In [30]:
np.log([0.000000000000000001])

array([-41.44653167])

In [38]:
eplison = 1e-15

In [39]:
y_predicted

array([1, 1, 0, 0, 1])

In [45]:
y_predicted_new = [max(i,eplison) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [46]:
y_predicted_new=[min(i,1-eplison) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [47]:
y_predicted_new= np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

> Log loss formula


In [48]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

> Formula in function

In [49]:
def log_loss(y_true,y_predicted):
    y_predicted_new = [max(i,eplison) for i in y_predicted]
    y_predicted_new = [min(i,1-eplison) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [50]:
log_loss(y_true,y_predicted)

17.2696280766844

> Exercise :<br>
Implement Mean squred error(MSE) in two ways:
1) without using numpy(i.e. using plain python)
2) with the use of numpy

>**MEAN SQUARED ERROR**

Loss function = (1/n) x (y-y&#770;)<sup>2</sup><br>
Cost function = (1/n) x &sum;<sub>i=1</sub><sup>n</sup>(y-y&#770;)<sup>2</sup>

> 1. without using numpy

In [51]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [53]:
def mse(y_true,y_predicted):
    for yt,yp in zip(y_true,y_predicted):
        print(yt,yp)

In [54]:
mse(y_true,y_predicted)

0.3 1
0.7 1
1.0 0
0.0 0
0.5 1


In [73]:
def mse(y_true,y_predicted):
    err = 0
    for yt,yp in zip(y_true,y_predicted):
        err += (yt-yp)**2
    mse = err/len(y_true)
    
    return mse

In [74]:
mse(y_true,y_predicted)

0.366

> 2. Using Numpy

In [59]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [60]:
np.square(y_true-y_predicted)

array([0.49, 0.09, 1.  , 0.  , 0.25])

In [61]:
np.mean(np.square(y_true-y_predicted))

0.366

<h4 style="color: red">Huber Loss</h4>

Combination of MSE and MAE<br>

loss = (1/n) x (y-y&#770;)<sup>2</sup> ; if |y-y&#770;| <= S (S for hyperparameter) ; no outliers <br>

&nbsp;&nbsp;&nbsp;= S|y-y&#770;|-1/2S<sup>2</sup>  ; otherwise (if outliers)

<h3 style="color: red">Conclusion</h3>

[hidden layer , output layer] = lossfunction <br><br>
[ReLU , softmax] = &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Categorical cross entropy<br>
[ReLU , sigmoid] = &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Binary cross Entropy(log loss)<br>
[ReLU , Linear] &nbsp;= &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;MSE,MAE,RMSE, Huberloss